networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - 5432:5432
    networks:
      - internal
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/${MEDIA_ROOT}
    depends_on:
      - db
    expose:
      - 8000:8000
    networks:
      - internal
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/${MEDIA_ROOT}
    depends_on:
      - backend


volumes:
  media_volume: